/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package arbol;

import java.util.ArrayList;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import utilidades.Archivo;

/**
 *
 * @author pablonoguera
 */
public class JframeTree extends javax.swing.JFrame {

    /**
     * Creates new form JframeTree
     */
    public JframeTree() {
        initComponents();
       
        Arbol arbol = Archivo.cargarDatos();
        DefaultMutableTreeNode padre = new DefaultMutableTreeNode("Costa Rica") ;
        DefaultTreeModel modelo = new DefaultTreeModel(padre);
        DefaultMutableTreeNode p1 = new DefaultMutableTreeNode("San José") ;
        ArrayList<String> cedulas =arbol.obtenerProvincia(1);
        for(int i = 0; i  < cedulas.size(); i ++){
            System.out.println(cedulas.get(i));
            p1.add(new DefaultMutableTreeNode(cedulas.get(i)));
        }
        DefaultMutableTreeNode p2 = new DefaultMutableTreeNode("Alajuela") ;
        cedulas =arbol.obtenerProvincia(2);
        for(int i = 0; i  < cedulas.size(); i ++){
            p2.add(new DefaultMutableTreeNode(cedulas.get(i)));
        }
        DefaultMutableTreeNode p3 = new DefaultMutableTreeNode("Cartago") ;
        cedulas =arbol.obtenerProvincia(3);
        for(int i = 0; i  < cedulas.size(); i ++){
            p3.add(new DefaultMutableTreeNode(cedulas.get(i)));
        }
        DefaultMutableTreeNode p4 = new DefaultMutableTreeNode("Heredia") ;
        cedulas =arbol.obtenerProvincia(4);
        for(int i = 0; i  < cedulas.size(); i ++){
            p4.add(new DefaultMutableTreeNode(cedulas.get(i)));
        }
        DefaultMutableTreeNode p5 = new DefaultMutableTreeNode("Guanacaste") ;
        cedulas =arbol.obtenerProvincia(5);
        for(int i = 0; i  < cedulas.size(); i ++){
            p5.add(new DefaultMutableTreeNode(cedulas.get(i)));
        }
        DefaultMutableTreeNode p6 = new DefaultMutableTreeNode("Punutarenas") ;
        cedulas =arbol.obtenerProvincia(6);
        for(int i = 0; i  < cedulas.size(); i ++){
            p6.add(new DefaultMutableTreeNode(cedulas.get(i)));
        }
        DefaultMutableTreeNode p7 = new DefaultMutableTreeNode("Limón") ;
        cedulas =arbol.obtenerProvincia(7);
        for(int i = 0; i  < cedulas.size(); i ++){
            p7.add(new DefaultMutableTreeNode(cedulas.get(i)));
        }
        DefaultMutableTreeNode p8 = new DefaultMutableTreeNode("Extranjero") ;
        cedulas =arbol.obtenerProvincia(8);
        for(int i = 0; i  < cedulas.size(); i ++){
            p8.add(new DefaultMutableTreeNode(cedulas.get(i)));
        }
        padre.add(p1);
        padre.add(p2);
        padre.add(p3);
        padre.add(p4);
        padre.add(p5);
        padre.add(p6);
        padre.add(p7);
        padre.add(p8);
        jTree1.setModel(modelo);
        
        System.out.println("Archivos cargados");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jTree1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(529, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JframeTree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JframeTree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JframeTree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JframeTree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JframeTree().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
